apiVersion: v1
kind: Service
metadata:
  name: springboot-backend
spec:
  selector:
    app: hello
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 8090
    targetPort: 8090
    nodePort: 30005
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: springboot-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: frontend
        track: stable
    spec:
      containers:
      - name: back
        image: back:v1
        # lifecycle:
          # preStop:
            # exec:
              # command: ["/usr/sbin/nginx","-s","quit"]
